Artificial Neural Network

Importing the Libraries

In [1]:
import numpy as np 
import pandas as pd 
import tensorflow as tf

In [2]:
tf.__version__

'2.16.2'

In [3]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values


In [4]:
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


Splitting Datraset into Training set and Test set

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

Feature Scaling

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
print(X_train)
print(X_test)

[[-1.75440309 -1.21216858  0.42112637  1.3027435 ]
 [ 0.41388954  0.88854693  0.23226259 -0.1942825 ]
 [-1.29005737 -1.15709364  0.83060976 -0.21559003]
 ...
 [-0.1419794  -1.16260113 -0.78392477 -0.32625174]
 [ 0.44619185 -0.73222983 -0.17387808 -1.54971652]
 [ 0.11509316 -0.36401453 -0.61010325 -0.17503699]]
[[-0.23081075 -0.76212765 -1.62294789  0.96594702]
 [-0.44481356 -0.94702209 -0.86415009 -1.4129359 ]
 [ 0.85131667  1.25912259 -0.96443174 -1.12356586]
 ...
 [-1.20660974 -1.25386817  1.26014949 -0.07056134]
 [ 1.93613595  1.51404088 -1.12989646 -1.53184568]
 [-0.58748211 -0.76606158  0.5347789   0.66764156]]


Initializing the ANN

In [8]:
ann = tf.keras.models.Sequential()

Adding the input layer and the first hidden layer

In [9]:
ann.add(tf.keras.layers.Dense(units = 6, activation='relu'))

Adding the second hidden layer

In [10]:
ann.add(tf.keras.layers.Dense(units = 6, activation='relu'))

Adding the output layer

In [11]:
ann.add(tf.keras.layers.Dense(units = 1))

Compiling the ANN

In [15]:
ann.compile(optimizer= 'adam', loss = tf.keras.losses.MeanSquaredError())

Training the ANN on the Training Set

In [16]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100


2025-01-08 12:00:27.770064: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


240/240 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.0000e+00 - loss: 205983.7031
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.0000e+00 - loss: 204528.1250
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.0000e+00 - loss: 200842.9531
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.0000e+00 - loss: 194910.2812
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.0000e+00 - loss: 187327.5000
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.0000e+00 - loss: 181881.2031
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.0000e+00 - loss: 176205.3750
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.0000e+00 - loss: 170275.3125
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.0000e+00 - loss: 163738.6875
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.0000e+00 - loss: 155827.8750
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/st

Predicting the result of the Test Set

In [17]:
y_pred = ann.predict(X_test)
# print [y_pred, y_test]
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
[[457.97570801 458.96      ]
 [466.08135986 463.29      ]
 [437.70956421 435.27      ]
 ...
 [477.8494873  476.22      ]
 [421.1763916  440.29      ]
 [465.14126587 467.92      ]]


Making the confusion matrix and score

In [19]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mse)
print("Mean Absolute Error:", mae)
print("R-squared Score:", r2)


Mean Squared Error: 22.484168330103106
Mean Absolute Error: 3.7358500411493027
R-squared Score: 0.9250003989812783
